config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  devise_for :users

  get '/contact', to: 'pages#show'
  post '/contact', to: 'pages#contact_email'


  get '/profile', to: 'profiles#show'
  post '/profile', to: 'profiles#create'
  get '/profile/edit', to: 'profiles#edit'
  patch '/profile', to: 'profiles#update'

  post '/requests/:request_id/offers', to: 'offers#create', as: 'requests_offer'
  

  resources :requests do
    resources :offers
  end

  resources :offers do
    member do
      post 'charge'
    end
  end

  # get 'offer/show', to: 'offers#show'

  # get '/requests/index', to: 'requests#index'
  # get '/requests/new', to: 'requests#new'
  # get '/request', to: 'requests#show'
  # post '/request', to: 'requests#create'
  # get '/request/edit', to: 'requests#edit'
  # patch '/request', to: 'requests#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :request

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  
  belongs_to :user
  has_many :offers
  
  accepts_nested_attributes_for :offers

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # example
  # current_user.profile.first_name
  # User.find(2).profile.first_name
  # makes your method singular
  has_one :profile
  has_many :requests
  has_many :offers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include Pundit

    protect_from_forgery with: :exception
    
    def after_sign_in_path_for(user)
        if user.profile.nil?
            profile_edit_path
        else
            root_path
        end
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  before_action :authenticate_user!
  before_action :set_offer, only: [:show, :edit, :update, :delete, :charge]

  def index
    puts "REQUEST_ID: #{params[:request_id]}"
    # @offers = Offer.all
    @offers = Offer.where(request_id: params[:request_id])
  end

  def new
    @offer = Offer.new
    @request = Request.find(params[:request_id])
  end

  def create
    offer = Offer.new(offer_params)
    request = Request.find(params[:request_id])
    
    offer.user = current_user
    offer.request = request

    if offer.save
      flash[:notice] = 'Parts Offer has been submitted. We will notify you if you offer has been accepted.'
      redirect_to root_path
    else
      flash[:alert] = 'Could not submit your parts offer.'
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @offer = Offer.find_or_initialize_by(user: current_user)
  end

  def show
    # @offer = Offer.find(offer_params)
    @offer = Offer.find(params[:id])
    # @offer.user = current_user
    # @offer = current_user.offer
    # @offer = Offer.find_or_initialize_by(user: current_user)

    # where request_id is current_request
    # show offers
  end


  # Stripe Method
  # posts/:id/booking
  def charge
    amount = @offer.price

    customer = Stripe::Customer.create(
      email:  params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,
      amount:       amount,
      description:  @offer.message,
      currency:     'aud'
    )

    flash[:notice] = 'Payment made!'

    redirect_to offers_path
  end
  
  private
  
  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:message, :price)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  

  def home
  end

  def contact_email
    user_info = {
      user: current_user,
      name: email_params[:name],
      message: email_params[:message],
    }
    ContactMailer.send_contact_email(user_info).deliver_now
    render :contact
  end

  private

  def email_params
    params.require(:contact).permit(:name, :message)
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    before_action :authenticate_user!

    def index
        authorize @profile
    end
    
    def show
        redirect_to :root unless user_signed_in?
        @profile = current_user.profile
    end

    def edit
        @profile = Profile.find_or_initialize_by(user: current_user)
    end
        
    def create
        @profile = Profile.new(profile_params)
        @profile.user = current_user

        if @profile.save
            flash[:notice] = 'Profile Updated'
            redirect_to root_path
        else
            flash[:alert] = 'Could not save profile'
            redirect_back(fallback_location: root_path)
        end
    end

    def update
        @profile = current_user.profile

        if @profile.update(profile_params)
            flash[:notice] = 'Profile Updated'
            redirect_to profile_path
        else
            flash[:alert] = 'Could not save profile'
            redirect_back(fallback_location: profile_path)
        end
    end

    private
    def profile_params
        params.require(:profile).permit(:first_name, :last_name, :street_number, :street_name, :suburb, :state, :postcode, :country)
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_request, only: [:show, :edit, :update, :destroy]

    def index
        @requests = Request.all
    end

    def show
    end

    def new
        @request = Request.new
    end

    def edit
        @request = Request.find_or_initialize_by(user: current_user)
        # @request = Request.find(request_params)
        @request = Request.find(params[:id])
        # @request = current_user.request
        @request.user = current_user 
    end

    def update
        @request.user = current_user

        if @request.update(request_params)
            flash[:notice] = 'Spare Parts Request Updated'
            redirect_to profile_path
        else
            flash[:alert] = 'Could not save spare parts request'
            redirect_back(fallback_location: profile_path)
        end
    end

    def destroy
    end

    def create
        @request = Request.new(request_params)
        @request.user = current_user

        if @request.save
            flash[:notice] = 'Thanks! Your Spare Parts Request has been Submitted. We will be in touch as soon as a parts offer has been recieved.'
            redirect_to profile_path
        else
            flash[:alert] = 'Could Not Save Spare Parts Request'
            redirect_back fallback_location: new_request_path
        end
    end


    private
    def request_params
        params.require(:request).permit(:part_name, :part_description, :car_make, :car_model, :car_series, :car_year, :image)
    end

    def set_request
        @request = Request.find(params[:id])
        authorize @request
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spare Me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site">
      <div class="site-content">
        <header class="site-header">
          <nav>
            <div id=logo>
              <a href="/" class="logo">SPARE<span>ME</span></a>
            </div>
            <ul>
              <% if user_signed_in? %>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to 'Profile', profile_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <% end %>
            </ul>
          </nav>
        </header>

        <%= yield %>

        <footer id="site-footer">
          <ul class="actions">
            <li><%= link_to 'About Us', contact_path %></li>
            <li><%= link_to 'Contact Us', contact_path %></li>
          </ul>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/offers/_charge_form.html.erb
<%= form_tag "/offers/#{@offer.id}/charge" do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="<%= @offer.message %>"
          data-amount="<%= @offer.price*100 %>"
          data-locale="auto"></script>
<% end %>

app/views/offers/_form.html.erb
<%= form_with(model: offer, url: requests_offer_path, local: true) do |f| %>

    <div class="field">  
        <%= f.label :message %><br />
        <%= f.text_area :message, autofocus: true, required: true  %>
    </div>

    <div class="field">  
        <%= f.label :price %><br />
        <%= f.number_field :price, required: true  %>
    </div>
    
    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/offers/_request_details.html.erb
<div class="offers-show">
    <div class="row">
        <li>
            <label>Part:</label>
            <output><%= @request.part_name %></output>
            <br>
            <br>
            <label>Description:</label>
            <output><%= @request.part_description %></output>
            <br>
            <br>
            <label>For:</label>
            <output><%= @request.car_year %> <%= @request.car_make %> <%= @request.car_model %></output>
            <br>
            <br>
            <output><%= image_tag @request.image_url(:medium) %></output>
        </li>
    </div>
</div>

app/views/offers/edit.html.erb
<h1>Offers#edit</h1>
<p>Find me in app/views/offers/edit.html.erb</p>

app/views/offers/index.html.erb
<div class="offers-show">
    <div class="row">
        <h3>Available Offers</h3>
        <ul class="offers-list">
            <% @offers.each do |offer| %>
            <li>
                <label>Message from supplier:</label>
                 <output><%= offer.message %></output>
                 <br>
                 <br>
                <label>Part Price:</label>
                <output><%= offer.price %></output>
            </li>
            <div class="accept-offer">
                <%= link_to  "Accept Offer", offer, class: "accept-offer-submit" %>
            </div>
            <% end %>
        </ul>
    </div>
</div>

app/views/offers/new.html.erb
<div class="offers-show">
    <div class="row">
    <h2>Send a Spare Parts Offer</h2>
        <ul class="offers-list">
            <li>
                <label>Part:</label>
                <output><%= @request.part_name %></output>
                <br>
                <br>
                <label>Description:</label>
                <output><%= @request.part_description %></output>
                <br>
                <br>
                <label>For:</label>
                <output><%= @request.car_year %> <%= @request.car_make %> <%= @request.car_model %></output>
                <br>
                <br>
                <output><%= image_tag @request.image_url(:medium) %></output>
                <br>
                <br>
                <%= render 'form', offer: @offer %>
            </li>
        </ul>
    </div>
</div>

app/views/offers/show.html.erb
<div class="offers-show">
  <div class="row">
    <h3>Offer Details</h3>
    <ul class="offers-list">
      <li>
        <label>Message:</label>
        <output><%= @offer.message %></output>
        <br>
        <br>
        <label>Price:</label>
        <output><%= @offer.price %></output>
      </li>
      <div class="stripe-pay">
        <% if user_signed_in? %>
          <%= render 'charge_form', post: @request %>
        <% else %>
          <%= link_to new_user_session_path, class:'stripe-button-el' do %>
            <span style="display: block; min-height: 30px;">Accept Offer and Buy</span>
            <% end %>
        <% end %>
      </div>
    </ul>
  </div>
</div>

app/views/pages/contact.html.erb
<h1> You email has been sent </h1>
<%= link_to 'Return Home', root_path %>

app/views/pages/home.html.erb
<div class="home-top-section">
    <div class="notice-container">
        <% if notice %>
            <p class="notice"><%= notice %></p>
        <% elsif alert %>
            <p class="alert"><%= alert %></p>
        <% end %>
    </div>
    <div class="home-tagline">
        <span>List Your Spare Parts Needs - Have the Market Come to You</span>
    </div>
</div>
<div class="home-bottom-section">
    <div class="home-buttons">
        <div class="submit">
            <%= link_to "Submit Parts Request", new_request_path, class: "button-submit" %>
        </div>

        <div class="browse">
            <%= link_to "Browse Parts Requests", requests_path, class: "button-browse" %>
        </div>
    </div>
</div>

app/views/pages/show.html.erb
<h1>Your Enquiry</h1>

<%= form_for :contact do |f| %>
    <p> <strong>
        <%= f.label :full_name %>
        <%= f.text_field :name %>
        </strong>
    </p>
    <p> 
        <strong>
        <%= f.label :message%>
        <%= f.text_area :message%>
        </strong>
    <p>    
        <%= f.submit "Send" %>
    </p>
<% end %>

app/views/profiles/edit.html.erb
<div class="profile-form">
    <div class="row">
        <h1>Your Profile</h1>
        <%= form_with(model: @profile, url: profile_path, local: true) do |form| %>
            <div class="field">
                <%= form.label :first_name %><br />
                <%= form.text_field :first_name, autofocus: true, required: true, :class => "form-field" %>
            </div>
            <br />
            <div class="field">
                <%= form.label :last_name %><br />
                <%= form.text_field :last_name, required: true, :class => "form-field" %>
            </div>
            <br />
            <div class="field">
                <%= form.label :street_number %><br />
                <%= form.number_field :street_number, required: true, :class => "form-field" %>
            </div>
            <br />
            <div class="field">
                <%= form.label :street_name %><br />
                <%= form.text_field :street_name, required: true, :class => "form-field" %>
            </div>
            <br />
            <div class="field">
                <%= form.label :suburb %><br />
                <%= form.text_field :suburb, required: true, :class => "form-field" %>
            </div>
            <br />
            <div class="field">
                <%= form.label :state %><br />
                <%= form.text_field :state, required: true, :class => "form-field" %>
            </div>
            <br />
            <div class="field">
                <%= form.label :postcode %><br />
                <%= form.number_field :postcode, required: true, :class => "form-field" %>
            </div>
            <br />
            <div class="field">
                <%= form.label :country %><br />
                <%= form.text_field :country, required: true, :class => "form-field" %>
            </div>
            <br />
            <p><span>Optional for Business Owners</span></p>
            <div class="field">
                <%= form.label :business_name %><br />
                <%= form.text_field :business_name, :class => "form-field" %>
            </div>
            <br />
            <div class="field">
                <%= form.label :business_number %><br />
                <%= form.text_field :business_number, :class => "form-field" %>
            </div>
            <p>
                <%= form.submit 'Update Profile', :class => 'submit-button' %>
            </p>
        <% end %>
    </div>
</div>

app/views/profiles/show.html.erb
<div class="profile-show">
    <div class="row">
        <h3>Your Profile</h3>
        <ul class="profile-list">
            <li>
                <label>First Name:</label>
                <output><%= @profile.first_name %></output>
            </li>
            <li>
                <label>Last Name:</label>
                <output><%= @profile.last_name %></output>
            </li> 
            <li>
                <label>Address:</label>
                <output><%= @profile.street_number %> <%= @profile.street_name %> <%= @profile.suburb %> <%= @profile.postcode %></output>
            </li>
            <li>
                <label>State:</label>
                <output><%= @profile.state %></output>
            </li> 
            <li>
                <label>Country:</label>
                <output><%= @profile.country %></output>
            </li>
            <div class="edit-profile">
                <%= link_to 'Edit Profile', profile_edit_path %>
            </div>
        </ul>
    </div>
</div>

<div class="profile-show">
    <div class="row">
    <h3>Your Parts Requests</h3>
        <% Request.where(user_id: current_user).find_each do |request| %>
            <ul class="profile-list">
                <li>
                    <label>Part:</label>
                    <output><%= request.part_name %></output>
                    <br>
                    <br>
                    <label>For:</label>
                    <output><%= request.car_year %> <%= request.car_make %> <%= request.car_model %></output>
                </li>
            </ul>
            <div class="show-request-button">
                <%= link_to  "See Request", request %>
            </div>
            
        <% end %>
    </div>
</div>

app/views/requests/_form.html.erb
<%= form_with(model: request, url: requests_path, local: true) do |f| %>

    <div class="field">  
        <%= f.label :part_name %><br />
        <%= f.text_field :part_name, autofocus: true, required: true, :class => "form-field" %>
    </div>
    <br />
    <div class="field">  
        <%= f.label :part_description %><br />
        <%= f.text_area :part_description, required: true, :class => "form-area" %>
    </div>
    <br />
    <div class="field">  
        <%= f.label :car_make %><br />
        <%= f.text_field :car_make, required: true, :class => "form-field" %>
    </div>
    <br />
    <div class="field">  
        <%= f.label :car_model %><br />
        <%= f.text_field :car_model, required: true, :class => "form-field" %>
    </div>
    <br />
    <div class="field">  
        <%= f.label :car_series %><br />
        <%= f.text_field :car_series, required: true, :class => "form-field" %>
    </div>
    <br />
    <div class="field">  
        <%= f.label :car_year %><br />
        <%= f.text_field :car_year, required: true, :class => "form-field" %>
    </div>
    <br />
    <div class="field">  
        <%= f.label :image %><br />
        <%= f.hidden_field :image, required: true, value: @request.cached_image_data %>
        <%= f.file_field :image %>
    </div>
    <br />
    <%= f.submit 'Submit Request', :class => 'submit-request-form-button'%>

<% end %>

app/views/requests/edit.html.erb
<h2>Edit Spare Parts Request</h2>

    <%= form_with(model: @request, url: request_path, local: true) do |f| %>

        <div class="field">  
            <%= f.label :part_name %><br />
            <%= f.text_field :part_name, autofocus: true, required: true  %>
        </div>
        <br>
        <div class="field">  
            <%= f.label :part_description %><br />
            <%= f.text_area :part_description, required: true  %>
        </div>
        <br>
        <div class="field">  
            <%= f.label :car_make %><br />
            <%= f.text_field :car_make  %>
        </div>
        <br>
        <div class="field">  
            <%= f.label :car_model %><br />
            <%= f.text_field :car_model %>
        </div>
        <br>
        <div class="field">  
            <%= f.label :car_series %><br />
            <%= f.text_field :car_series %>
        </div>
        <br>
        <div class="field">  
            <%= f.label :car_year %><br />
            <%= f.text_field :car_year %>
        </div>
        <br>
        <div class="field">  
            <%= f.label :image %><br />
            <%= f.hidden_field :image, value: @request.cached_image_data %>
            <%= f.file_field :image %>
        </div>
        <br>
        <p>
            <%= f.submit %>
        </p>
    <% end %>
    </div>
</div>

app/views/requests/index.html.erb
<div class="requests-show">
    <div class="row">
        <h2>Browse Requests</h2>
        <ul class="requests-list">
            <% @requests.each do |request| %>
            <li>
                <label>Part:</label>
                <output><%= request.part_name %></output>
                <br>
                <br>
                <label>Description:</label>
                <output><%= request.part_description %></output>
                <br>
                <br>
                <label>For:</label>
                <output><%= request.car_year %> <%= request.car_make %> <%= request.car_model %></output>
                <br>
                <br>
                <output><%= image_tag request.image_url(:thumb) %></output>
            </li>
            <div class="show-request">
                <%= link_to  "Show Request", request %>
            </div>
            <% end %>
        </ul>
    </div>
</div>

app/views/requests/new.html.erb
<div class="request-form">
    <div class="row">
        <h2>Request a Spare Part</h2>
        <%= render 'form', request: @request %>
    </div>
</div>

app/views/requests/show.html.erb
<div class="see-parts-request">
    <div class="row">
    <h2>Parts Request</h2>
        <ul class="see-request-content">
            <li>
                <label>Part:</label>
                <output><%= @request.part_name %></output>
                <br>
                <br>
                <label>Description:</label>
                <output><%= @request.part_description %></output>
                <br>
                <br>
                <label>For:</label>
                <output><%= @request.car_year %> <%= @request.car_make %> <%= @request.car_model %></output>
                <br>
                <br>
                <output><%= image_tag @request.image_url(:medium) %></output>
            </li>
        </ul>

        <div class="requests-buttons">
            <% if policy(@request).edit? %>
            <div class="edit">
                <%= link_to  "Edit Request", edit_request_path, class: "button-submit"  %>
            </div>
            <% end %>
            <div class="show">
                <%= link_to  "View Offers", request_offers_path(@request), class: "button-submit" %>
            </div>
            <div class="offer">
                <%= link_to "Offer Part", new_request_offer_path(@request), class: "button-submit" %>
            </div>
        </div>
    </div>
</div>